# Generated by Django 4.0.3 on 2023-01-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_automobilevo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='employee',
        ),
        migrations.AddField(
            model_name='sales',
            name='employee',
            field=models.ManyToManyField(to='sales_rest.employees'),
        ),
    ]
