# Generated by Django 4.0.3 on 2023-01-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_remove_sales_employee_sales_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ManyToManyField(to='sales_rest.customers'),
        ),
    ]
