# Generated by Django 4.0.3 on 2023-01-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_remove_sales_customer_sales_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='sales_rest.customers'),
        ),
        migrations.RemoveField(
            model_name='sales',
            name='employee',
        ),
        migrations.AddField(
            model_name='sales',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='sales_rest.employees'),
        ),
    ]
