# Generated by Django 4.0.3 on 2023-01-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0009_remove_sales_customer_sales_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_vehicle', to='sales_rest.automobilevo'),
        ),
    ]
