# Generated by Django 4.0.3 on 2023-01-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0010_alter_sales_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
