# Generated by Django 4.0.3 on 2023-01-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0011_sales_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_price',
            field=models.BigIntegerField(),
        ),
    ]
