# Generated by Django 4.0.3 on 2023-01-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0012_alter_sales_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='name',
        ),
    ]
